Merge branch 'master', remote-tracking branch 'remotes/proj1/master' into HEAD
ERROR:     java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:5)
        at com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(com.google.firebase:firebase-auth@@19.2.0:255)
        at com.example.gantt.LoginFragment.onCreateView(LoginFragment.kt:47)

# Conflicts:
#	app/build.gradle
#	app/src/main/java/com/example/gantt/MainActivity.kt
#	build.gradle